version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Specify a docker image
    steps:
      - checkout
      - run:
          name: Build the app
          command: gcloud app deploy

workflows:
  build_app:
    jobs:
      - build:
          filters:
            branches:
              only: master
