version: 2.1


jobs:
  test:
    working_directory: ~/app/PetfinderServer
    docker:
      - image: eeacms/pyflakes:py3
    steps:
      - checkout
      - run:
          name: Check syntax
          command: pyflakes main.py

  deploy:
    docker:
      - image: google/cloud-sdk:latest 
        auth:
          username: liam.doan22@imperial.ac.uk
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run:
          name: Dump GCloud Credentials to file
          command: echo ${GCLOUD_SERVICE_KEY} > ./gcp-key.json
      - run:
          name: Authenticate service account
          command: |
            echo $GCLOUD_SERVICE_KEY > key.json
            gcloud auth activate-service-account app-engine-deployment@petfinder-424117.iam.gserviceaccount.com --key-file key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            # gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud app deploy


workflows:
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master

