version: 2.1

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:latest
        auth: _json_key
        password: $GOOGLE_CREDENTIALS

    steps:
      - checkout
      - run: 
          name: Deploy to Google App Engine
          command: gcloud app deploy --project $GCLOUD_PROJECT --quiet

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

