version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - run: gcloud app deploy

workflows:
  build_app:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

