version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Specify a docker image
    steps:
      - checkout
      - run:
        name: Download the Gcloud 
        command: curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-473.0.0-linux-x86_64.tar.gz
      - run:
        name: unzip the Gcloud
        command: tar -xvf google-cloud-cli-473.0.0-linux-x86_64.tar.gz
      - run:
        name: install the Gcloud
        command: ./google-cloud-sdk/install.sh
      - run:
        name: Authenticate with Google Cloud
        command: gcloud auth login --cred-file=$CLOUDSDK_AUTH_ACCESS_TOKEN
      - run:
          name: Build the app
          command: gcloud app deploy

workflows:
  build_app:
    jobs:
      - build:
          filters:
            branches:
              only: master
