version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.0.0

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - gcp-cli/initialize:
          gcloud-service-key: $GOOGLE_CREDENTIALS
          project-id: $GCLOUD_PROJECT
      - run: 
          name: Deploy to Google App Engine
          command: gcloud app deploy --project $GCLOUD_PROJECT --quiet

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

