version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
        auth:
          username: mydockerhub-user
          password: $CLOUDSDK_AUTH_ACCESS_TOKEN  # context / project UI env-var reference
    steps:
      - run: gcloud app deploy

workflows:
  build_app:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

