version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Specify a docker image
    steps:
      - checkout
      - run:
          name: Install Google Cloud SDK
          command: |
            curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-323.0.0-linux-x86_64.tar.gz
            tar -xzvf google-cloud-sdk-323.0.0-linux-x86_64.tar.gz
            ./google-cloud-sdk/install.sh
            source ./google-cloud-sdk/path.bash.inc
      - run:
          name: Authenticate with Google Cloud
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
      - run:
          name: Configure gcloud
          command: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run:
          name: Set project
          command: gcloud config set project <YOUR_PROJECT_ID>
      - run:
          name: Build the app
          command: gcloud app deploy

workflows:
  build_app:
    jobs:
      - build:
          filters:
            branches:
              only: master
